"""Add due_date to Task

Revision ID: 242142601a9f
Revises: 9880dd2d0522
Create Date: 2025-06-13 05:57:38.671185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242142601a9f'
down_revision = '9880dd2d0522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
