"""create subtasks table

Revision ID: edfba8c7e4a7
Revises: 242142601a9f
Create Date: 2025-06-14 12:17:45.576078
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfba8c7e4a7'
down_revision = '242142601a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtasks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=255), nullable=False),
                    sa.Column('completed', sa.Boolean(), nullable=False),
                    sa.Column('task_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtasks')
    # ### end Alembic commands ###
